import cx_Oracle
from flask import Flask
from flask_socketio import SocketIO

socketio = SocketIO()

def create_app():
    app = Flask(__name__)

    # Konfigurasi koneksi ke Oracle
    ORACLE_USERNAME = "askrindo"
    ORACLE_PASSWORD = "askrindo"
    ORACLE_HOST = "192.168.30.132"
    ORACLE_PORT = "1531"
    ORACLE_SERVICE_NAME = "FREEPDB1"

    # Membuat string koneksi
    dsn = cx_Oracle.makedsn(ORACLE_HOST, ORACLE_PORT, service_name=ORACLE_SERVICE_NAME)
    connection = cx_Oracle.connect(user=ORACLE_USERNAME, password=ORACLE_PASSWORD, dsn=dsn)
    cursor = connection.cursor()

    # Simpan koneksi dalam app config
    app.config["ORACLE_CONNECTION"] = connection

    # Membuat tabel jika belum ada
    create_tables(cursor)

    return app

def create_tables(cursor):
    # Tabel test_vector2
    cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE 'CREATE TABLE test_vector2 (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                filename VARCHAR2(255),
                text CLOB,
                text_vector CLOB
            )';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
        END;
    """)

    # Tabel chat_history
    cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE 'CREATE TABLE chat_history (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_input CLOB,
                bot_response CLOB,
                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
        END;
    """)
